import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocaleNotifier extends StateNotifier<String> {
  static const _key = 'app_locale';

  LocaleNotifier() : super('en') {
    _loadLocale();
  }

  Future<void> _loadLocale() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLocale = prefs.getString(_key);
      if (savedLocale != null) {
        state = savedLocale;
      }
    } catch (_) {}
  }

  Future<void> setLocale(String locale) async {
    state = locale;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_key, locale);
    } catch (_) {}
  }
}

final localeProvider = StateNotifierProvider<LocaleNotifier, String>((ref) {
  return LocaleNotifier();
});

const Map<String, String> languageNames = {
  'en': 'English',
  'si': 'සිංහල (Sinhala)',
  'ta': 'தமிழ் (Tamil)',
  'hi': 'हिन्दी (Hindi)',
  'id': 'Bahasa Indonesia',
  'zh': '中文 (Chinese)',
};

const Map<String, Map<String, String>> _translations = {
  'en': {
    'welcome_title': 'MokoGuard AI',
    'welcome_tagline': 'Detect Banana Leaf Diseases Offline instantly with Explainable AI Diagnostics.',
    'get_started': 'Get Started',
    'next': 'Next',
    'skip': 'Skip',
    'scan_leaves': 'Scan Leaves',
    'scan_leaves_desc': 'Quickly capture photos of suspicious banana leaves in the field, or crop multiple leaves inside one parent image.',
    'detect_disease': 'Detect Disease Offline',
    'detect_disease_desc': 'Edge AI analyzes symptoms instantly without internet, highlighting affected lesions using explainable Grad-CAM heatmaps.',
    'treat_protect': 'Treat & Protect',
    'treat_protect_desc': 'Read targeted agricultural treatment guidelines matched by severity, and export tree status reports to offline PDFs.',
    'welcome_back': 'Welcome to MokoGuard AI',
    'offline_intel': 'Offline Explainable Banana Disease Intelligence',
    'weather_alert': 'Weather Alert: Sigatoka Risk',
    'weather_desc': 'High humidity (84%) & rainfall detected. Sigatoka spore activity is highly active. Consider checking inner foliage.',
    'total_scans': 'Total Scans',
    'healthy': 'Healthy',
    'diseased': 'Diseased',
    'moko_wilts': 'Moko Wilts',
    'disease_dist': 'Disease Distribution',
    'no_dist': 'No diagnostics recorded yet',
    'scan_leaf_btn': 'Scan Leaf',
    'full_history_btn': 'Full History',
    'recent_diagnostics': 'Recent Diagnostics',
    'no_prev_diagnostics': 'No previous diagnostics',
    'dashboard_tab': 'Dashboard',
    'guide_tab': 'Guide',
    'analytics_tab': 'Analytics',
    'settings_tab': 'Settings',
    'feedback_prompt': 'Was this diagnosis correct?',
    'feedback_correct': 'Correct Class',
    'feedback_severity': 'Correct Severity',
    'feedback_submit': 'Submit Feedback',
    'feedback_thanks': 'Thank you! Your feedback helps retrain MokoGuard AI.',
    'feedback_privacy': 'Feedback data is stored locally and anonymously on this device.',
    'feedback_improve': 'Help improve the app by providing correct details:',
    'confidence': 'Confidence',
    'disease_Black_Sigatoka': 'Black Sigatoka',
    'disease_Cordana': 'Cordana Leaf Spot',
    'disease_Healthy': 'Healthy Leaf',
    'disease_Panama_Disease': 'Panama Disease',
    'disease_Pestalotiopsis': 'Pestalotiopsis Leaf Spot',
    'disease_Yellow_Sigatoka': 'Yellow Sigatoka',
    'disease_Moko': 'Moko Disease',
    'severity_Low': 'Low Severity',
    'severity_Medium': 'Medium Severity',
    'severity_High': 'High Severity',
    'diagnostic_results': 'Diagnostic Results',
    'low_light_badge': 'Low Light Enhanced',
    'low_light_title': 'Low-Light Auto Enhancement',
    'low_light_desc': 'This photo was taken in low light and enhanced automatically to improve diagnosis accuracy.',
    'compare_original_enhanced': 'Compare Original vs Enhanced',
    'view_mode_original': 'Original',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': 'Severity',
    'view_mode_combined': 'Combined',
    'view_mode_overlay': 'Overlay',
    'latency': 'Latency',
    'status': 'Status',
    'status_archived': 'Archived',
    'status_temporary': 'Temporary',
    'save_to_history': 'Save to History',
    'saved_to_history': 'Saved to History',
    'export_pdf_report': 'Export PDF Report',
    'treatment_recommendations': 'Treatment Recommendations',
    'enable_research_mode': 'Enable Research Mode',
    'overlay_opacity': 'Overlay Opacity',
    'severity_legend': 'Severity Color Legend',
    'legend_low': 'Low / Healthy (<10%)',
    'legend_medium': 'Medium (10%-40%)',
    'legend_high': 'High (>40%)',
    'tree_level_diagnosis': 'Tree-Level Diagnosis',
    'save_tree_to_history': 'Save Tree to History',
    'tree_saved': 'Tree Saved',
    'export_aggregated_report': 'Export Aggregated Report',
    'individual_leaf_breakdown': 'Individual Leaf Breakdown',
    'tree_level_action': 'Tree-Level Action Guidelines',
    'leaf_crop_num': 'Leaf Crop {number}',
    'leaf_crop_details': 'Leaf Crop #{number} Details',
    'probability_distribution': 'Probability Distribution:',
    'settings_title': 'Settings & Controls',
    'settings_subtitle': 'Configure offline model versions, research modes, and local database settings',
    'appearance_header': 'Appearance',
    'theme_settings': 'Theme Settings',
    'theme_dark': 'Dark Mode Active',
    'theme_light': 'Light Mode Active',
    'language_settings': 'Language Settings',
    'language_subtitle': 'Select application language',
    'ai_research_header': 'AI Model & Research Tools',
    'model_version_title': 'Inference Model Version',
    'model_version_desc': 'Select offline neural network file',
    'research_mode_title': 'Academic Research Mode',
    'research_mode_desc': 'Expose raw output logit distributions & diagnostic stats',
    'image_quality_header': 'Image Quality & Enhancement',
    'low_light_enhancement_title': 'Auto Low-Light Enhancement',
    'low_light_enhancement_desc': 'Improve dark or low-contrast photos before analysis',
    'enhancement_strength_title': 'Enhancement Strength',
    'enhancement_strength_desc': 'Set CLAHE & Gamma correction level',
    'local_data_header': 'Local Data Controls',
    'export_history_title': 'Export Scan History',
    'export_history_desc': 'Save database log as a portable JSON file',
    'export_feedback_json_title': 'Export Feedback (JSON)',
    'export_feedback_json_desc': 'Save user feedback logs as a JSON file',
    'export_feedback_csv_title': 'Export Feedback (CSV)',
    'export_feedback_csv_desc': 'Save user feedback logs as a tabular CSV file',
    'clear_data_title': 'Clear All Diagnostic Data',
    'clear_data_desc': 'Permanently reset scanning database logs',
    'analytics_title': 'Analytics & Trends',
    'analytics_subtitle': 'Diagnostic History Analysis and Plantation Health Trends',
    'weekly_volume': 'Weekly Diagnostic Volume',
    'weekly_volume_desc': 'Number of leaf scans performed daily over the last 7 days',
    'key_indicators': 'Key Health Indicators',
    'healthy_rate_card': 'Healthy Crop Rate',
    'primary_threat_card': 'Primary Threat',
    'avg_confidence_card': 'Avg. Confidence',
    'alert_status_card': 'Alert Status',
    'alert_status_low': 'LOW',
    'alert_status_warning': 'WARNING',
    'alert_status_critical': 'CRITICAL',
    'plantation_insight_title': 'Plantation Insight',
    'insight_empty': 'Start scanning leaf samples in the field to automatically generate local agricultural insights here.',
    'insight_healthy': 'Your plantation shows excellent health metrics! Maintain present crop protection protocols and routine irrigation.',
    'insight_critical_desc': 'Warning: {disease} outbreaks detected. Clean all tools with sterilizer immediately and isolate the affected zones.',
    'insight_warning_desc': 'A few leaf spot infections have been logged. Monitor secondary leaves closely and keep deleafing infected parts.',
    'active_learning_card': 'Active Learning & User Corrections',
    'active_learning_desc': 'Academic data validation tracking from on-device user feedback loops.',
    'feedback_rate_label': 'Feedback Rate',
    'logs_count_label': 'Logs Count',
    'thumbs_down_label': 'Thumbs Down',
    'top_corrections_label': 'Top User Correction Mappings:',
    'corrections_count': '{count} corrections',
    'active_learning_context': 'Active Learning Context: These anonymized corrective records help compile high-fidelity datasets. Researchers can export this data in Settings as CSV/JSON to perform active learning fine-tuning for subsequent CNN iterations.',
    'none': 'None',
    'education_title': 'Education Guide',
    'education_subtitle': 'Offline Database of Banana Disease Symptoms and Control Methods',
    'education_search_hint': 'Search symptoms, pathogens...',
    'no_matches_found': 'No matches found for "{query}"',
    'pathogen_label': 'Pathogen',
    'severity_levels_label': 'Severity Levels',
    'symptoms_label': 'Symptoms',
    'management_header': 'Management & Control',
    'management_cultural': 'Cultural Practices',
    'management_organic': 'Organic Methods',
    'management_chemical': 'Chemical Methods',
    'management_prevention': 'Prevention',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'learn_more': 'Learn More',
    'source_label': 'Source: {source}',
    'cat_Normal_Status': 'Normal Status',
    'cat_Bacterial_Wilt': 'Bacterial Wilt (High Severity)',
    'cat_Fungal_Wilt': 'Fungal Wilt (High Severity)',
    'cat_Fungal_Leaf_Spot': 'Fungal Leaf Spot',
    'cat_Fungal_Infection': 'Fungal Infection',
    
    // Black Sigatoka
    'disease_Black_Sigatoka_symptoms': 'Starts with small yellow/reddish specks on the underside of leaves. Turns into long black streaks and spots with yellow halos. Severe cases cause leaves to dry and hang down.',
    'disease_Black_Sigatoka_severity': 'Low (<10%), Medium (10–40%), High (>40%)',
    'disease_Black_Sigatoka_mgmt_cultural': '• Remove and burn all infected leaves regularly.\n• Improve spacing between plants for better air flow.\n• Improve drainage to reduce humidity.\n• Prune old leaves (de-leafing).',
    'disease_Black_Sigatoka_mgmt_organic': '• Spray neem oil mixed with soap.\n• Use baking soda + soap solution.\n• Apply mustard or garlic plant extracts as border spray.',
    'disease_Black_Sigatoka_mgmt_chemical': '• Use fungicides recommended by Department of Agriculture Sri Lanka (such as Propiconazole, Mancozeb).\n• Rotate different fungicides to prevent resistance.',
    'disease_Black_Sigatoka_mgmt_prevention': '• Plant resistant banana varieties when available.\n• Use balanced fertilizer (avoid too much nitrogen).\n• Regular field cleaning and monitoring.',

    // Yellow Sigatoka
    'disease_Yellow_Sigatoka_symptoms': 'Pale yellow streaks on upper leaf surface that turn into brown spots with yellow halos. Leaves dry quickly.',
    'disease_Yellow_Sigatoka_severity': 'Low, Medium, High',
    'disease_Yellow_Sigatoka_mgmt_cultural': '• Remove and burn infected leaves immediately.\n• Improve air circulation by proper spacing.\n• Ensure good drainage to avoid waterlogging.',
    'disease_Yellow_Sigatoka_mgmt_organic': '• Neem oil spray.\n• Baking soda + soap water spray.',
    'disease_Yellow_Sigatoka_mgmt_chemical': '• Apply recommended fungicides (Propiconazole or Mancozeb) at early stage.\n• Follow DOA guidelines and rotate chemicals.',
    'disease_Yellow_Sigatoka_mgmt_prevention': '• Regular de-leafing.\n• Use healthy planting material.\n• Maintain balanced nutrition.',

    // Moko Disease
    'disease_Moko_symptoms': 'Sudden yellowing and wilting of leaves. Brown streaks inside stem. Fruit shows internal rot. Bacterial ooze comes out when cut.',
    'disease_Moko_severity': 'Low, Medium, High',
    'disease_Moko_mgmt_cultural': '• Immediately remove and destroy the entire infected plant + nearby suckers.\n• Disinfect all tools with bleach after use.\n• Remove male flower buds regularly using a forked stick.',
    'disease_Moko_mgmt_organic': '• No effective organic cure once infected.',
    'disease_Moko_mgmt_chemical': '• No effective chemical cure for infected plants.',
    'disease_Moko_mgmt_prevention': '• Use only disease-free planting material.\n• Avoid planting in previously infected soil.\n• Proper field hygiene and tool disinfection.',

    // Panama Disease
    'disease_Panama_Disease_symptoms': 'Yellowing of older leaves, leaves collapse like a skirt. Reddish-brown color inside the stem.',
    'disease_Panama_Disease_severity': 'Low, Medium, High',
    'disease_Panama_Disease_mgmt_cultural': '• Remove and destroy entire infected plant + soil around roots.\n• Do not move soil from infected areas.',
    'disease_Panama_Disease_mgmt_organic': '• Limited effectiveness.',
    'disease_Panama_Disease_mgmt_chemical': '• No effective chemical cure once soil is infected.',
    'disease_Panama_Disease_mgmt_prevention': '• Use certified disease-free tissue culture plants.\n• Plant resistant varieties if available.\n• Long crop rotation (do not plant banana in same field for many years).\n• Avoid using infected farm tools.',

    // Cordana
    'disease_Cordana_symptoms': 'Large oval or diamond-shaped pale brown spots with yellow borders and rings.',
    'disease_Cordana_severity': 'Low, Medium, High',
    'disease_Cordana_mgmt_cultural': '• Remove and burn infected leaves.\n• Improve air flow and spacing.\n• Reduce humidity by better drainage.',
    'disease_Cordana_mgmt_organic': '• Neem oil spray.',
    'disease_Cordana_mgmt_chemical': '• Use recommended fungicides when infection spreads.',
    'disease_Cordana_mgmt_prevention': '• Regular field monitoring.\n• Balanced fertilizer application.',

    // Pestalotiopsis
    'disease_Pestalotiopsis_symptoms': 'Small brown/grey spots with dark borders that can merge into large dead areas.',
    'disease_Pestalotiopsis_severity': 'Low, Medium, High',
    'disease_Pestalotiopsis_mgmt_cultural': '• Remove infected leaves promptly.\n• Maintain good field hygiene.\n• Avoid excess nitrogen fertilizer.',
    'disease_Pestalotiopsis_mgmt_organic': '• Neem oil or plant extract sprays.',
    'disease_Pestalotiopsis_mgmt_chemical': '• Apply fungicides only when necessary.',
    'disease_Pestalotiopsis_mgmt_prevention': '• Use balanced fertilizer.\n• Proper spacing and drainage.',

    // Healthy Leaf
    'disease_Healthy_symptoms': 'Bright green, clean leaves with no spots or yellowing.',
    'disease_Healthy_severity': 'Healthy (No infection)',
    'disease_Healthy_mgmt_cultural': '• Regular de-leafing of old leaves.\n• Proper spacing and pruning.',
    'disease_Healthy_mgmt_organic': '• Use compost and organic manure.',
    'disease_Healthy_mgmt_chemical': '• Not needed if plant is healthy.',
    'disease_Healthy_mgmt_prevention': '• Balanced fertilizer (Nitrogen, Phosphorus, Potassium).\n• Proper irrigation and drainage.\n• Regular monitoring with MokoGuard AI.',
  },
  'si': {
    'welcome_title': 'මොකොගාඩ් AI',
    'welcome_tagline': 'අන්තර්ජාලය නොමැතිව කෙසෙල් කොළ රෝග හඳුනාගෙන පැහැදිලි AI විශ්ලේෂණ ලබා ගන්න.',
    'get_started': 'ආරම්භ කරන්න',
    'next': 'මීළඟ',
    'skip': 'මඟහරින්න',
    'scan_leaves': 'කොළ ස්කෑන් කරන්න',
    'scan_leaves_desc': 'වගා බිමේ ඇති සැක සහිත කෙසෙල් කොළවල ඡායාරූප ඉක්මනින් ලබා ගන්න, නැතහොත් එක් ඡායාරූපයකින් කොළ කිහිපයක් කපා වෙන්කරන්න.',
    'detect_disease': 'offline රෝග හඳුනාගැනීම',
    'detect_disease_desc': 'අන්තර්ජාලය නොමැතිව ක්‍රියාත්මක වන AI මගින් රෝග ලක්ෂණ ක්ෂණිකව විශ්ලේෂණය කර Grad-CAM තාප සිතියම් මගින් රෝගී ප්‍රදේශ පෙන්වයි.',
    'treat_protect': 'ප්‍රතිකාර සහ ආරක්ෂාව',
    'treat_protect_desc': 'රෝගී තදබදය අනුව සකස් කළ කෘෂිකාර්මික උපදෙස් කියවන්න, සහ වගා වාර්තා PDF ගොනු ලෙස ලබා ගන්න.',
    'welcome_back': 'මොකොගාඩ් AI වෙත සාදරයෙන් පිළිගනිමු',
    'offline_intel': 'අන්තර්ජාලයෙන් තොර කෙසෙල් රෝග හඳුනාගැනීමේ තාක්ෂණය',
    'weather_alert': 'කාලගුණ අනතුරු ඇඟවීම: සිගටෝකා අවදානම',
    'weather_desc': 'ඉහළ ආර්ද්‍රතාවය (84%) සහ වර්ෂාපතනය හඳුනාගෙන ඇත. සිගටෝකා බීජාණු සක්‍රීය බැවින් කොළ පරීක්ෂා කරන්න.',
    'total_scans': 'මුළු ස්කෑන්',
    'healthy': 'නිරෝගී',
    'diseased': 'රෝගී',
    'moko_wilts': 'මොකෝ රෝගය',
    'disease_dist': 'රෝග ව්‍යාප්තිය',
    'no_dist': 'තවමත් දත්ත කිසිවක් සටහන් වී නැත',
    'scan_leaf_btn': 'කොළය ස්කෑන් කරන්න',
    'full_history_btn': 'ඉතිහාසය',
    'recent_diagnostics': 'මෑතකදී සිදුකල පරීක්ෂණ',
    'no_prev_diagnostics': 'මෑතකදී සිදුකල පරීක්ෂණ නොමැත',
    'dashboard_tab': 'ප්‍රධාන පුවරුව',
    'guide_tab': 'මඟපෙන්වීම',
    'analytics_tab': 'විශ්ලේෂණ',
    'settings_tab': 'සැකසුම්',
    'feedback_prompt': 'මෙම හඳුනාගැනීම නිවැරදිද?',
    'feedback_correct': 'නිවැරදි රෝගය',
    'feedback_severity': 'නිවැරදි බරපතලකම',
    'feedback_submit': 'ප්‍රතිචාර යොමු කරන්න',
    'feedback_thanks': 'ස්තූතියි! ඔබගේ ප්‍රතිචාරය මොකොගාඩ් AI වැඩිදියුණු කිරීමට උපකාරී වේ.',
    'feedback_privacy': 'ප්‍රතිචාර දත්ත මෙම උපාංගයේ පමණක් සුරැකේ.',
    'feedback_improve': 'නිවැරදි තොරතුරු ලබා දීමෙන් යෙදුම වැඩිදියුණු කිරීමට උදවු වන්න:',
    'confidence': 'විශ්වාසනීයත්වය',
    'disease_Black_Sigatoka': 'කළු සිගටෝකා (Black Sigatoka)',
    'disease_Cordana': 'කෝඩනා කොළ ලප රෝගය (Cordana)',
    'disease_Healthy': 'නිරෝගී පත්‍රය (Healthy)',
    'disease_Panama_Disease': 'පැනමා රෝගය (Panama Disease)',
    'disease_Pestalotiopsis': 'පෙස්ටලෝටියොප්සිස් (Pestalotiopsis)',
    'disease_Yellow_Sigatoka': 'කහ සිගටෝකා (Yellow Sigatoka)',
    'disease_Moko': 'මොකෝ රෝගය (Moko)',
    'severity_Low': 'අඩු බරපතලකම',
    'severity_Medium': 'මධ්‍යම බරපතලකම',
    'severity_High': 'ඉහළ බරපතලකම',
    'diagnostic_results': 'පරීක්ෂණ ප්‍රතිඵල',
    'low_light_badge': 'අඩු ආලෝකය වැඩි දියුණු කරන ලදි',
    'low_light_title': 'අඩු ආලෝකය ස්වයංක්‍රීයව වැඩි දියුණු කිරීම',
    'low_light_desc': 'මෙම ඡායාරූපය අඩු ආලෝකයේදී ගන්නා ලද අතර රෝග විනිශ්චය නිවැරදි කිරීම සඳහා ස්වයංක්‍රීයව වැඩි දියුණු කරන ලදි.',
    'compare_original_enhanced': 'මුල් ඡායාරූපය සහ වැඩි දියුණු කල ඡායාරූපය සංසන්දනය කරන්න',
    'view_mode_original': 'මුල් පෙනුම',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': 'බරපතලකම',
    'view_mode_combined': 'සංයුක්ත',
    'view_mode_overlay': 'වැස්ම',
    'latency': 'ප්‍රතිචාර කාලය',
    'status': 'තත්ත්වය',
    'status_archived': 'සුරකින ලද',
    'status_temporary': 'තාවකාලික',
    'save_to_history': 'ඉතිහාසයට එක් කරන්න',
    'saved_to_history': 'ඉතිහාසයට එක් කරන ලදි',
    'export_pdf_report': 'PDF වාර්තාව ලබා ගන්න',
    'treatment_recommendations': 'නිර්දේශිත ප්‍රතිකාර ක්‍රම',
    'enable_research_mode': 'පර්යේෂණ මාදිලිය සක්‍රීය කරන්න',
    'overlay_opacity': 'පැහැදිලි බව',
    'severity_legend': 'වර්ණ සලකුණු පැහැදිලි කිරීම',
    'legend_low': 'අඩු / නිරෝගී (<10%)',
    'legend_medium': 'මධ්‍යම (10%-40%)',
    'legend_high': 'ඉහළ (>40%)',
    'tree_level_diagnosis': 'ගස මට්ටමේ රෝග විනිශ්චය',
    'save_tree_to_history': 'සම්පූර්ණ ගසේ දත්ත සුරකින්න',
    'tree_saved': 'ගසේ දත්ත සුරකින ලදි',
    'export_aggregated_report': 'සංයුක්ත වාර්තාව ලබා ගන්න',
    'individual_leaf_breakdown': 'එක් එක් පත්‍ර වල තත්ත්වය',
    'tree_level_action': 'ගස සඳහා නිර්දේශිත ක්‍රියාමාර්ග',
    'leaf_crop_num': 'පත්‍ර කොටස {number}',
    'leaf_crop_details': 'පත්‍ර කොටස #{number} හි විස්තර',
    'probability_distribution': 'සම්භාවිතා ව්‍යාප්තිය:',
    'settings_title': 'සැකසුම් සහ පාලනයන්',
    'settings_subtitle': 'මාදිලි සංස්කරණ, පර්යේෂණ ආකාර සහ දත්ත සමුදා සැකසුම් සකසන්න',
    'appearance_header': 'පෙනුම (Appearance)',
    'theme_settings': 'තේමා සැකසුම්',
    'theme_dark': 'අඳුරු මාදිලිය සක්‍රීයයි',
    'theme_light': 'ආලෝක මාදිලිය සක්‍රීයයි',
    'language_settings': 'භාෂා සැකසුම්',
    'language_subtitle': 'යෙදුමේ භාෂාව තෝරන්න',
    'ai_research_header': 'AI ආකෘති සහ පර්යේෂණ මෙවලම්',
    'model_version_title': 'AI ආකෘති සංස්කරණය',
    'model_version_desc': 'offline ක්‍රියාත්මක වන AI ආකෘති ගොනුව තෝරන්න',
    'research_mode_title': 'ශාස්ත්‍රීය පර්යේෂණ මාදිලිය',
    'research_mode_desc': 'අමු ප්‍රතිදාන සහ රෝග විනිශ්චය සංඛ්‍යාලේඛන පෙන්වන්න',
    'image_quality_header': 'පින්තූරයේ ගුණාත්මකභාවය සහ වැඩිදියුණු කිරීම',
    'low_light_enhancement_title': 'ස්වයංක්‍රීය අඩු ආලෝක වැඩිදියුණු කිරීම',
    'low_light_enhancement_desc': 'විශ්ලේෂණයට පෙර අඳුරු හෝ අඩු වෙනසක් ඇති ඡායාරූප වැඩි දියුණු කරන්න',
    'enhancement_strength_title': 'වැඩිදියුණු කිරීමේ ප්‍රමාණය',
    'enhancement_strength_desc': 'CLAHE සහ ගැමා නිවැරදි කිරීමේ මට්ටම සකසන්න',
    'local_data_header': 'දේශීය දත්ත පාලනයන්',
    'export_history_title': 'ස්කෑන් ඉතිහාසය අපනයනය කරන්න',
    'export_history_desc': 'දත්ත සමුදාය ජංගම JSON ගොනුවක් ලෙස සුරකින්න',
    'export_feedback_json_title': 'ප්‍රතිචාර අපනයනය කරන්න (JSON)',
    'export_feedback_json_desc': 'ප්‍රතිචාර දත්ත JSON ගොනුවක් ලෙස සුරකින්න',
    'export_feedback_csv_title': 'ප්‍රතිචාර අපනයනය කරන්න (CSV)',
    'export_feedback_csv_desc': 'ප්‍රතිචාර දත්ත පැතුරුම්පත් CSV ගොනුවක් ලෙස සුරකින්න',
    'clear_data_title': 'සියලුම රෝග විනිශ්චය දත්ත මකන්න',
    'clear_data_desc': 'දේශීය රෝග විනිශ්චය දත්ත සටහන් ස්ථිරවම මකන්න',
    'analytics_title': 'විශ්ලේෂණ සහ ප්‍රවණතා',
    'analytics_subtitle': 'රෝග විනිශ්චය ඉතිහාස විශ්ලේෂණය සහ වගා සෞඛ්‍ය ප්‍රවණතා',
    'weekly_volume': 'සතිපතා රෝග විනිශ්චය ප්‍රමාණය',
    'weekly_volume_desc': 'පසුගිය දින 7 තුළ දිනපතා සිදු කරන ලද කොළ ස්කෑන් ගණන',
    'key_indicators': 'ප්‍රධාන සෞඛ්‍ය දර්ශක',
    'healthy_rate_card': 'නිරෝගී බෝග ප්‍රතිශතය',
    'primary_threat_card': 'ප්‍රධාන තර්ජනය',
    'avg_confidence_card': 'සාමාන්‍ය විශ්වාසනීයත්වය',
    'alert_status_card': 'අනතුරු ඇඟවීමේ තත්ත්වය',
    'alert_status_low': 'අඩු',
    'alert_status_warning': 'අවවාදාත්මක',
    'alert_status_critical': 'අතිශය බරපතල',
    'plantation_insight_title': 'වගා බිම් නිරීක්ෂණ',
    'insight_empty': 'දේශීය කෘෂිකාර්මික නිරීක්ෂණ මෙහි ස්වයංක්‍රීයව ජනනය කිරීම සඳහා ක්ෂේත්‍රයේ කොළ සාම්පල ස්කෑන් කිරීම ආරම්භ කරන්න.',
    'insight_healthy': 'ඔබගේ වගා බිම විශිෂ්ට සෞඛ්‍ය දර්ශක පෙන්වයි! වත්මන් බෝග ආරක්ෂණ ක්‍රම සහ නිතිපතා ජල සම්පාදනය පවත්වා ගන්න.',
    'insight_critical_desc': 'අනතුරු ඇඟවීමයි: {disease} රෝගී තත්ත්වයන් වාර්තා වී ඇත. වහාම සියලුම මෙවලම් විෂබීජහරණය කර ආසාදිත ප්‍රදේශ වෙන් කරන්න.',
    'insight_warning_desc': 'කොළ ලප රෝග ආසාදන කිහිපයක් සටහන් වී ඇත. ද්විතීයික පත්‍ර සමීපව නිරීක්ෂණය කර ආසාදිත කොටස් කපා ඉවත් කරන්න.',
    'active_learning_card': 'සක්‍රීය ඉගෙනීම සහ පරිශීලක සංශෝධන',
    'active_learning_desc': 'උපාංගය තුළ සිදුවන පරිශීලක ප්‍රතිචාර මඟින් අධ්‍යයන දත්ත වල නිවැරදිභාවය නිරීක්ෂණය කිරීම.',
    'feedback_rate_label': 'ප්‍රතිචාර අනුපාතය',
    'logs_count_label': 'වාර්තා ගණන',
    'thumbs_down_label': 'වැරදි විනිශ්චයන්',
    'top_corrections_label': 'ප්‍රධාන පරිශීලක සංශෝධන සිතියම්කරණය:',
    'corrections_count': 'සංශෝධන {count}',
    'active_learning_context': 'සක්‍රීය ඉගෙනුම් සන්දර්භය: මෙම නිර්නාමික සංශෝධන වාර්තා උසස් තත්ත්වයේ දත්ත කට්ටල සකස් කිරීමට උපකාරී වේ. ඊළඟ CNN පුහුණු කිරීම් සඳහා Settings මඟින් මෙම දත්ත CSV/JSON ලෙස අපනයනය කළ හැක.',
    'none': 'නැත',
    'education_title': 'මඟපෙන්වීමේ පොත',
    'education_subtitle': 'කෙසෙල් කොළ රෝග ලක්ෂණ සහ පාලන ක්‍රම පිළිබඳ නොබැඳි (Offline) දත්ත පදනම',
    'education_search_hint': 'රෝග ලක්ෂණ, රෝග කාරකයන් සොයන්න...',
    'no_matches_found': '"{query}" සඳහා ගැලපීම් කිසිවක් හමු නොවීය',
    'prevention_label': 'වැළැක්වීම සහ පාලන ක්‍රම',
    'cat_Normal_Status': 'සාමාන්‍ය තත්ත්වය',
    'cat_Bacterial_Wilt': 'බැක්ටීරියා මැලවීම (ඉහළ බරපතලකම)',
    'cat_Fungal_Wilt': 'දිලීර මැලවීම (ඉහළ බරපතලකම)',
    'cat_Fungal_Leaf_Spot': 'දිලීර කොළ ලප රෝග',
    'cat_Fungal_Infection': 'දිලීර ආසාදනය',
    'disease_Healthy_symptoms': 'ක්‍රියාකාරී ප්‍රභාසංශ්ලේෂණ හැකියාව, ඒකාකාරී නහර සහ සුමට දාර සහිත සීරීම් රහිත හරිත පත්‍ර. මැලවීමක්, කහ පැහැති දාර හෝ වියළි පටක විනාශ වීමේ ලප නොමැත.',
    'disease_Healthy_prevention': 'නිතිපතා ජල සම්පාදනය පවත්වා ගැනීම, පසෙහි NPK මට්ටම් සමතුලිත කිරීම, නිතිපතා වල් නෙලීම සහ ආර්ද්‍රතාවය අවම කිරීම සඳහා ගස් අතර ප්‍රමාණවත් පරතරයක් තබා ගැනීම.',
    'disease_Moko_symptoms': 'ඇතුළත කොළ වලින් ආරම්භ වී පත්‍ර තල වේගයෙන් කහ වීම සහ මැලවීම. කොළ නටුව ළඟින් කැඩී පහළට එල්ලේ. කඳ කැපූ විට දුඹුරු පැහැති වාහිනී අවපැහැ ගැන්වීමක් පෙන්වයි.',
    'disease_Moko_prevention': 'දැඩි නිරෝධායන නීති ක්‍රියාත්මක කරන්න. ආසාදිත ශාක වහාම විනාශ කරන්න. නිරෝගී ගස් වෙත යාමට පෙර ගොවිපල මෙවලම් (පිහි, කැති) 10% ෆෝමල්ඩිහයිඩ් හෝ තාපයෙන් විෂබීජහරණය කරන්න. වාහක කෘමීන් පාලනය කරන්න.',
    'disease_Panama_Disease_symptoms': 'පැරණි කොළවල දාරවලින් ආරම්භ වී මැද නහර දෙසට පැතිරෙන ලා කහ පැහැයක්. කොළ මැලවී, පාමුලින් නැමී ව්‍යාජ කඳ වටා වියළුණු කොළ සායක් සාදයි. ඇතුළත රතු-දුඹුරු ඉරි පෙන්වයි.',
    'disease_Panama_Disease_prevention': 'සහතික කළ රෝගවලින් තොර පටක රෝපිත පැළ භාවිත කරන්න. ආසාදිත කලාපවල භාවිතා කළ උපකරණ පිරිසිදු වගාබිම්වල භාවිතයෙන් වළකින්න. පසට ට්‍රයිකොඩර්මා (Trichoderma) වැනි ජෛව පාලක යොදන්න. ප්‍රතිරෝධී ප්‍රභේද වගා කරන්න.',
    'disease_Black_Sigatoka_symptoms': 'කොළයේ යටි පැත්තේ කුඩා තද දුඹුරු පැහැති ලප ඇති වී පසුව නහරවලට සමාන්තරව තද ඉරි බවට පත්වේ. මෙම ඉරි ජලයෙන් පෙඟුණු දාර සහ කහ පැහැති වටකුරු දාර සහිත විශාල කළු ලප බවට පත්වේ.',
    'disease_Black_Sigatoka_prevention': 'වගාවේ ජලාපවහනය වැඩි දියුණු කරන්න, ආර්ද්‍රතාවය අඩු කිරීමට පැරණි කොළ කපා දමන්න, වායු සංසරණය වැඩි කිරීමට නිසි පරතරය තබන්න, සහ අවදානම් කාලවලදී දිලීර නාශක (තඹ දිලීර නාශක) භාවිතා කරන්න.',
    'disease_Yellow_Sigatoka_symptoms': 'කොළ නහරවලට සමාන්තරව ඇතිවන ලා කහ-කොළ පැහැති ඉරි. මෙම ඉරි මධ්‍යයේ ලා අළු පැහැයක්, තද දුඹුරු දාර සහ දීප්තිමත් කහ පැහැති වටකුරු දාර සහිත ඕවලාකාර ලප බවට පත්වේ.',
    'disease_Yellow_Sigatoka_prevention': 'ආසාදිත කොටස් අඛණ්ඩව කපා ඉවත් කරන්න. ගස් ශක්තිමත්ව තබා ගැනීමට වල් පාලනය සහ පොහොර යෙදීම සහතික කරන්න. ආසාදන මට්ටම අනුව පද්ධතිමය හෝ ස්පර්ශක දිලීර නාශක යොදන්න.',
    'disease_Cordana_symptoms': 'සාමාන්‍ยයෙන් පත්‍ර දාරවලින් ආරම්භ වන විශාල, ඕවලාකාර හෝ පටි වැනි ලප. මෙම ලප ලා අළු සහ තද දුඹුරු වළලු සහිත සිග්-සැග් (zig-zag) හැඩැති දාර සලකුණු පෙන්වයි.',
    'disease_Cordana_prevention': 'බීජාණු පැතිරීම වැළැක්වීම සඳහා වගා බිමෙන් වියළි කොළ සුන්බුන් ඉවත් කරන්න. පත්‍ර පටක ශක්තිමත් කිරීම සඳහා පසෙහි පොටෑසියම් මට්ටම සමතුලිතව පවත්වා ගන්න.',
    'disease_Pestalotiopsis_symptoms': 'සාමාන්‍යයෙන් යාන්ත්‍රික තුවාල හෝ කෘමි හානිවලින් ආරම්භ වන වියළි අළු-දුඹුරු පටක විනාශ වීමේ ලප. ලපයේ මධ්‍යය අළු පැහැ වන අතර කුඩා කළු ලප (බීජාණු ව්‍යුහයන්) දැකිය හැක.',
    'disease_Pestalotiopsis_prevention': 'ප්‍රවාහනයේදී හෝ වල් නෙලීමේදී කොළ වලට යාන්ත්‍රික තුවාල සිදුවීම වළක්වන්න. බීජාණු ඇතුළු වන තුවාල ඇති කරන කෘමීන් පාලනය කරන්න. රෝගය පැතිරී ඇත්නම් ආරක්ෂිත තඹ ඉසින යොදන්න.',
    'pathogen_label': 'රෝග කාරකය',
    'severity_levels_label': 'බරපතලකම් මට්ටම්',
    'symptoms_label': 'රෝග ලක්ෂණ',
    'management_header': 'කළමනාකරණය සහ පාලනය',
    'management_cultural': 'සංස්කෘතික ක්‍රමවේද',
    'management_organic': 'කාබනික ක්‍රමවේද',
    'management_chemical': 'රසායනික ක්‍රමවේද',
    'management_prevention': 'වැළැක්වීම',
    'low': 'අඩු',
    'medium': 'මධ්‍යම',
    'high': 'ඉහළ',
    'learn_more': 'තව දැනගන්න',
    'source_label': 'මූලාශ්‍රය: {source}',
  },
  'ta': {
    'welcome_title': 'மொக்கோகார்ட் AI',
    'welcome_tagline': 'இணையம் இல்லாமல் வாழை இலை நோய்களைக் கண்டறிந்து AI விளக்கங்களைப் பெறுங்கள்.',
    'get_started': 'தொடங்குங்கள்',
    'next': 'அடுத்து',
    'skip': 'தவிர்க்க',
    'scan_leaves': 'இலைகளை ஸ்கேன் செய்க',
    'scan_leaves_desc': 'தோட்டத்தில் உள்ள சந்தேகத்திற்கிடமான வாழை இலைகளை விரைவாக புகைப்படம் எடுங்கள், அல்லது ஒரே படத்தில் பல இலைகளை வெட்டுங்கள்.',
    'detect_disease': 'இணையமில்லா கண்டறிதல்',
    'detect_disease_desc': 'AI மூலம் நோய் அறிகுறிகளை உடனடியாக பகுப்பாய்வு செய்து Grad-CAM வெப்ப வரைபடங்களை உருவாக்குகிறது.',
    'treat_protect': 'சிகிச்சை & பாதுகாப்பு',
    'treat_protect_desc': 'பாதிப்பு நிலைக்கு ஏற்ப விவசாய சிகிச்சை வழிகாட்டுதல்களைப் படித்து PDF அறிக்கையாக ஏற்றுமதி செய்க.',
    'welcome_back': 'மொக்கோகார்ட் AI-க்கு வரவேற்கிறோம்',
    'offline_intel': 'வாழை நோய் கண்டறிதல் மற்றும் பகுப்பாய்வு தொழில்நுட்பம்',
    'weather_alert': 'வானிலை எச்சரிக்கை: சிகடோகா ஆபத்து',
    'weather_desc': 'அதிக ஈரப்பதம் (84%) மற்றும் மழை கண்டறியப்பட்டுள்ளது. சிகடோகா பரவல் அதிகமாக உள்ளது.',
    'total_scans': 'மொத்த ஸ்கேன்',
    'healthy': 'ஆரோக்கியமானது',
    'diseased': 'பாதிக்கப்பட்டது',
    'moko_wilts': 'மொக்கோ வாடல்',
    'disease_dist': 'நோய் பரவல்',
    'no_dist': 'தரவுகள் எதுவும் இன்னும் பதிவு செய்யப்படவில்லை',
    'scan_leaf_btn': 'இலையை ஸ்கேன் செய்',
    'full_history_btn': 'முழு வரலாறு',
    'recent_diagnostics': 'சமீபத்திய பரிசோதனைகள்',
    'no_prev_diagnostics': 'முந்தைய பரிசோதனைகள் எதுவுமில்லை',
    'dashboard_tab': 'முகப்பு',
    'guide_tab': 'வழிகாட்டி',
    'analytics_tab': 'பகுப்பாய்வு',
    'settings_tab': 'அமைப்புகள்',
    'feedback_prompt': 'இந்த பகுப்பாய்வு சரியானதா?',
    'feedback_correct': 'சரியான வகை',
    'feedback_severity': 'சரியான பாதிப்பு',
    'feedback_submit': 'பதிலை சமர்ப்பி',
    'feedback_thanks': 'நன்றி! உங்களது பதில் மொக்கோகார்ட் AI-ஐ மேம்படுத்த உதவும்.',
    'feedback_privacy': 'பதில்கள் இந்த சாதனத்தில் மட்டுமே சேமிக்கப்படும்.',
    'feedback_improve': 'சரியான விவரங்களை வழங்கி செயலியை மேம்படுத்த உதவவும்:',
    'confidence': 'நம்பகத்தன்மை',
    'disease_Black_Sigatoka': 'கருப்பு சிகடோகா (Black Sigatoka)',
    'disease_Cordana': 'கோர்டானா இலைப்புள்ளி (Cordana)',
    'disease_Healthy': 'ஆரோக்கியமான இலை (Healthy)',
    'disease_Panama_Disease': 'பனாமா நோய் (Panama Disease)',
    'disease_Pestalotiopsis': 'பெஸ்டலோடியாப்சிஸ் (Pestalotiopsis)',
    'disease_Yellow_Sigatoka': 'மஞ்சள் சிகடோகா (Yellow Sigatoka)',
    'disease_Moko': 'மொக்கோ நோய் (Moko)',
    'severity_Low': 'குறைந்த பாதிப்பு',
    'severity_Medium': 'நடுத்தர பாதிப்பு',
    'severity_High': 'அதிக பாதிப்பு',
    'diagnostic_results': 'பரிசோதனை முடிவுகள்',
    'low_light_badge': 'குறைந்த ஒளி மேம்படுத்தப்பட்டது',
    'low_light_title': 'குறைந்த ஒளி தானியங்கி மேம்பாடு',
    'low_light_desc': 'இந்தப் படம் குறைந்த ஒளியில் எடுக்கப்பட்டது, கண்டறிதல் துல்லியத்தை மேம்படுத்த தானாகவே மேம்படுத்தப்பட்டது.',
    'compare_original_enhanced': 'அசல் மற்றும் மேம்படுத்தப்பட்டதை ஒப்பிடுக',
    'view_mode_original': 'அசல்',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': 'பாதிப்பு',
    'view_mode_combined': 'கூட்டு',
    'view_mode_overlay': 'மேலடுக்கு',
    'latency': 'பகுப்பாய்வு நேரம்',
    'status': 'நிலை',
    'status_archived': 'சேமிக்கப்பட்டது',
    'status_temporary': 'தற்காலிகமானது',
    'save_to_history': 'வரலாற்றில் சேமி',
    'saved_to_history': 'வரலாற்றில் சேமிக்கப்பட்டது',
    'export_pdf_report': 'PDF அறிக்கையை ஏற்றுமதி செய்',
    'treatment_recommendations': 'சிகிச்சை பரிந்துரைகள்',
    'enable_research_mode': 'ஆராய்ச்சி பயன்முறையை இயக்கு',
    'overlay_opacity': 'ஒளி ஊடுருவல்',
    'severity_legend': 'பாதிப்பு வண்ணக்குறியீடு விளக்கம்',
    'legend_low': 'குறைந்த / ஆரோக்கியம் (<10%)',
    'legend_medium': 'நடுத்தர (10%-40%)',
    'legend_high': 'அதிக (>40%)',
    'tree_level_diagnosis': 'மர அளவிலான கண்டறிதல்',
    'save_tree_to_history': 'மர விவரங்களை சேமி',
    'tree_saved': 'மர விவரங்கள் சேமிக்கப்பட்டது',
    'export_aggregated_report': 'தொகுப்பு அறிக்கையை ஏற்றுமதி செய்',
    'individual_leaf_breakdown': 'தனித்தனி இலைகளின் விவரம்',
    'tree_level_action': 'மர அளவிலான நடவடிக்கை வழிகாட்டுதல்',
    'leaf_crop_num': 'இலை பகுதி {number}',
    'leaf_crop_details': 'இலை பகுதி #{number} விவரங்கள்',
    'probability_distribution': 'சம்பவத்தகவு விநியோகம்:',
    'settings_title': 'அமைப்புகள் மற்றும் கட்டுப்பாடுகள்',
    'settings_subtitle': 'மாடல் பதிப்புகள், ஆராய்ச்சி முறைகள் மற்றும் உள்ளூர் தரவுத்தள அமைப்புகளை உள்ளமைக்கவும்',
    'appearance_header': 'தோற்றம்',
    'theme_settings': 'தீம் அமைப்புகள்',
    'theme_dark': 'இருண்ட பயன்முறை செயலில் உள்ளது',
    'theme_light': 'ஒளி பயன்முறை செயலில் உள்ளது',
    'language_settings': 'மொழி அமைப்புகள்',
    'language_subtitle': 'செயலி மொழியைத் தேர்ந்தெடுக்கவும்',
    'ai_research_header': 'AI மாடல் & ஆராய்ச்சி கருவிகள்',
    'model_version_title': 'கண்டறிதல் மாடல் பதிப்பு',
    'model_version_desc': 'ஆஃப்லைன் நரம்பியல் பிணையக் கோப்பைத் தேர்ந்தெடுக்கவும்',
    'research_mode_title': 'கல்வி ஆராய்ச்சி பயன்முறை',
    'research_mode_desc': 'மூல வெளியீடு மற்றும் கண்டறிதல் புள்ளிவிவரங்களைக் காண்பி',
    'image_quality_header': 'படத்தின் தரம் மற்றும் மேம்பாடு',
    'low_light_enhancement_title': 'தானியங்கி குறைந்த ஒளி மேம்பாடு',
    'low_light_enhancement_desc': 'பகுப்பாய்வுக்கு முன் இருண்ட அல்லது குறைந்த மாறுபட்ட புகைப்படங்களை மேம்படுத்தவும்',
    'enhancement_strength_title': 'மேம்படுத்தும் அளவு',
    'enhancement_strength_desc': 'CLAHE & காமா திருத்த அளவை அமைக்கவும்',
    'local_data_header': 'உள்ளூர் தரவு கட்டுப்பாடுகள்',
    'export_history_title': 'பகுப்பாய்வு வரலாற்றை ஏற்றுமதி செய்',
    'export_history_desc': 'தரவுத்தள பதிவை JSON கோப்பாக சேமிக்கவும்',
    'export_feedback_json_title': 'பதில்களை ஏற்றுமதி செய் (JSON)',
    'export_feedback_json_desc': 'பயனர் கருத்துப் பதிவுகளை JSON கோப்பாக சேமிக்கவும்',
    'export_feedback_csv_title': 'பதில்களை ஏற்றுமதி செய் (CSV)',
    'export_feedback_csv_desc': 'பயனர் கருத்துப் பதிவுகளை CSV கோப்பாக சேமிக்கவும்',
    'clear_data_title': 'அனைத்து தரவுகளையும் அழி',
    'clear_data_desc': 'உள்ளூர் பகுப்பாய்வு தரவுகளை நிரந்தரமாக மீட்டமைக்கவும்',
    'analytics_title': 'பகுப்பாய்வு மற்றும் போக்குகள்',
    'analytics_subtitle': 'கண்டறிதல் வரலாற்று பகுப்பாய்வு மற்றும் தோட்ட சுகாதார போக்குகள்',
    'weekly_volume': 'வாராந்திர கண்டறிதல் அளவு',
    'weekly_volume_desc': 'கடந்த 7 நாட்களில் தினமும் செய்யப்பட்ட இலை ஸ்கேன்களின் எண்ணிக்கை',
    'key_indicators': 'முக்கிய சுகாதார குறிகாட்டிகள்',
    'healthy_rate_card': 'ஆரோக்கியமான பயிர் விகிதம்',
    'primary_threat_card': 'முக்கிய அச்சுறுத்தல்',
    'avg_confidence_card': 'சராசரி நம்பிக்கை நிலை',
    'alert_status_card': 'எச்சரிக்கை நிலை',
    'alert_status_low': 'குறைவு',
    'alert_status_warning': 'எச்சரிக்கை',
    'alert_status_critical': 'மிகவும் ஆபத்தானது',
    'plantation_insight_title': 'தோட்ட நுண்ணறிவு',
    'insight_empty': 'உள்ளூர் விவசாய நுண்ணறிவுகளை தானாக உருவாக்க இலையின் மாதிரிகளை ஸ்கேன் செய்யத் தொடங்குங்கள்.',
    'insight_healthy': 'உங்கள் தோட்டம் சிறந்த சுகாதார குறிகாட்டிகளைக் காட்டுகிறது! தற்போதைய பாதுகாப்பு முறைகளையும் வழக்கமான நீர் பாசனத்தையும் பராமரிக்கவும்.',
    'insight_critical_desc': 'எச்சரிக்கை: {disease} பாதிப்புகள் கண்டறியப்பட்டுள்ளன. உடனடியாக அனைத்து கருவிகளையும் கிருமி நீக்கம் செய்து பாதிக்கப்பட்ட பகுதிகளைத் தனிமைப்படுத்தவும்.',
    'insight_warning_desc': 'சில இலைப்புள்ளி தொற்றுகள் பதிவாகியுள்ளன. இரண்டாம் நிலை இலைகளை உன்னிப்பாகக் கண்காணித்து, பாதிக்கப்பட்ட இலைகளை வெட்டி அகற்றவும்.',
    'active_learning_card': 'செயலில் கற்றல் & பயனர் திருத்தங்கள்',
    'active_learning_desc': 'சாதனத்தில் உள்ள கருத்துக்களிலிருந்து கல்வித் தரவு சரிபார்ப்பு கண்காணிப்பு.',
    'feedback_rate_label': 'கருத்து விகிதம்',
    'logs_count_label': 'பதிவுகளின் எண்ணிக்கை',
    'thumbs_down_label': 'தவறான கண்டறிதல்கள்',
    'top_corrections_label': 'முக்கிய பயனர் திருத்த வரைபடங்கள்:',
    'corrections_count': 'திருத்தங்கள் {count}',
    'active_learning_context': 'செயலில் கற்றல் சூழல்: இந்த அநாமதேய திருத்தப் பதிவுகள் தரவுத்தொகுப்புகளை உருவாக்க உதவுகின்றன. ஆராய்ச்சியாளர்கள் இந்தத் தரவை அமைப்புகளில் CSV/JSON ஆக ஏற்றுமதி செய்யலாம்.',
    'none': 'ஏதுமில்லை',
    'education_title': 'கல்வி வழிகாட்டி',
    'education_subtitle': 'வாழை நோய் அறிகுறிகள் மற்றும் கட்டுப்பாட்டு முறைகளின் ஆஃப்லைன் தரவுத்தளம்',
    'education_search_hint': 'அறிகுறிகள், நோய்க்கிருமிகளைத் தேடுங்கள்...',
    'no_matches_found': '"{query}"-க்கு பொருத்தங்கள் எதுவும் கிடைக்கவில்லை',
    'prevention_label': 'தடுப்பு மற்றும் கட்டுப்பாட்டு முறைகள்',
    'cat_Normal_Status': 'சாதாரண நிலை',
    'cat_Bacterial_Wilt': 'பாக்டீரியா வாடல் (அதிக பாதிப்பு)',
    'cat_Fungal_Wilt': 'பூஞ்சை வாடல் (அதிக பாதிப்பு)',
    'cat_Fungal_Leaf_Spot': 'பூஞ்சை இலைப்புள்ளி',
    'cat_Fungal_Infection': 'பூஞ்சை தொற்று',
    'disease_Healthy_symptoms': 'செயலில் உள்ள ஒளிச்சேர்க்கை திறன், சீரான நரம்புகள் மற்றும் மென்மையான விளிம்புகளுடன் கூடிய தழும்பற்ற பச்சை இலைகள். வாடல், விளிம்பு மஞ்சள் நிறமாதல் அல்லது உலர் திசு இறப்பு புள்ளிகள் இல்லை.',
    'disease_Healthy_prevention': 'வழக்கமான நீர் பாசனத்தை பராமரிக்கவும், மண்ணில் NPK அளவை சமநிலைப்படுத்தவும், தவறாமல் களை எடுக்கவும், ஈரப்பதத்தை குறைக்க மரங்களுக்கு இடையே போதிய இடைவெளியை பராமரிக்கவும்.',
    'disease_Moko_symptoms': 'உள் இலைகளில் இருந்து தொடங்கி இலைப்பகுதி வேகமாக மஞ்சள் நிறமாகi வாடுதல். இலைக்காம்பு உடைந்து கீழ்நோக்கி தொங்கும். தண்டினை வெட்டும்போது பழுப்பு நிற வாஸ்குலர் நிறமாற்றம் தெரியும்.',
    'disease_Moko_prevention': 'கடுமையான தனிமைப்படுத்தலை அமல்படுத்துங்கள். பாதிக்கப்பட்ட தாவரங்களை உடனடியாக அழிக்கவும். சுத்தமான மரங்களுக்குச் செல்வதற்கு முன் விவசாயக் கருவிகளை 10% ஃபார்மால்டிஹைட் அல்லது வெப்பத்தால் கிருமி நீக்கம் செய்யவும். பூச்சிகளைக் கட்டுப்படுத்தவும்.',
    'disease_Panama_Disease_symptoms': 'பழைய இலைகளின் விளிம்புகளில் லேசான மஞ்சள் நிறமாகி நடு நரம்பு நோக்கி பரவுதல். இலைகள் வாடி, அடியில் மடிந்து தண்டைச் சுற்றி காய்ந்த இலைகளின் ஓரடுக்கு உருவாகும். உட்புற தண்டு சிவப்பு-பழுப்பு கோடுகளைக் காட்டும்.',
    'disease_Panama_Disease_prevention': 'சான்றளிக்கப்பட்ட திசு வளர்ப்பு நாற்றுகளைப் பயன்படுத்தவும். பாதிக்கப்பட்ட பகுதிகளில் பயன்படுத்திய கருவிகளை சுத்தமான நிலங்களில் பயன்படுத்த வேண்டாம். மண்ணில் டிரைக்கோடெர்மா போன்ற உயிர் கட்டுப்பாட்டு முகவர்களைப் பயன்படுத்தவும்.',
    'disease_Black_Sigatoka_symptoms': 'இலையின் அடிப்பகுதியில் சிறிய கரும்பழுப்பு நிற புள்ளிகள் தோன்றி, நரம்புகளுக்கு இணையாக கருப்பு கோடுகளாக மாறும். கோடுகள் மஞ்சள் நிற வளையங்களுடன் பெரிய நீள்வட்ட கருப்பு புள்ளிகளாக விரிவடையும்.',
    'disease_Black_Sigatoka_prevention': 'வடிகால் வசதியை மேம்படுத்தவும், ஈரப்பதத்தை குறைக்க பழைய இலைகளை கவாத்து செய்யவும், காற்று ஓட்டத்தை அதிகரிக்க இடைவெளி விடவும் மற்றும் ஆபத்தான காலங்களில் பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்.',
    'disease_Yellow_Sigatoka_symptoms': 'இலை நரம்புகளுக்கு இணையாக வெளிர் மஞ்சள்-பச்சை கோடுகள். கோடுகள் சாம்பல் நிற மையங்கள், கரும்பழுப்பு நிற எல்லைகள் மற்றும் பிரகாசமான மஞ்சள் வளையங்களுடன் நீள்வட்ட புள்ளிகளாக மாறும்.',
    'disease_Yellow_Sigatoka_prevention': 'பாதிக்கப்பட்ட பகுதிகளைத் தொடர்ந்து அகற்றவும். மரங்களை வலுவாக வைத்திருக்க களை கட்டுப்பாடு மற்றும் உரமிடுதலை உறுதி செய்யவும். தொற்றின் அளவைப் பொறுத்து பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்.',
    'disease_Cordana_symptoms': 'பொதுவாக இலை விளிம்புகளில் இருந்து தொடங்கும் பெரிய, ஓவல் அல்லது பட்டை போன்ற புள்ளிகள். புள்ளிகள் வெளிர் சாம்பல் மற்றும் கரும்பழுப்பு நிற செறிவூட்டப்பட்ட வளையங்களுடன் கூடிய கோண வடிவ எல்லையைக் கொண்டுள்ளன.',
    'disease_Cordana_prevention': 'பூஞ்சை பரவுவதைத் தடுக்க காய்ந்த இலை கழிவுகளை தோட்டத்திலிருந்து அகற்றவும். இலை திசுக்களை வலுப்படுத்த மண்ணில் பொட்டாசியம் அளவை சமநிலையில் பராமரிக்கவும்.',
    'disease_Pestalotiopsis_symptoms': 'பொதுவாக இயந்திர காயங்கள் அல்லது பூச்சி கடித்தலில் இருந்து தொடங்கும் உலர் சாம்பல்-பழுப்பு நிற திசு இறப்பு புள்ளிகள். புள்ளியின் மையம் சாம்பal நிறமாகி சிறிய கருப்பு புள்ளிகளைக் காட்டும்.',
    'disease_Pestalotiopsis_prevention': 'போக்குவரத்து அல்லது களை எடுக்கும்போது இலைகளில் காயம் ஏற்படுவதைத் தவிர்க்கவும். பூஞ்சை நுழையும் காயங்களை ஏற்படுத்தும் பூச்சிகளை நிர்வகிக்கவும். தேவைப்பட்டால் தாமிர தெளிப்புகளைப் பயன்படுத்தவும்.',
    'pathogen_label': 'நோய்க்கிருமி',
    'severity_levels_label': 'பாதிப்பு நிலைகள்',
    'symptoms_label': 'அறிகுறிகள்',
    'management_header': 'மேலாண்மை மற்றும் கட்டுப்பாடு',
    'management_cultural': 'வளர்ப்பு முறைகள்',
    'management_organic': 'இயற்கை முறைகள்',
    'management_chemical': 'இரசாயன முறைகள்',
    'management_prevention': 'தடுப்பு முறைகள்',
    'low': 'குறைந்த',
    'medium': 'நடுத்தர',
    'high': 'அதிக',
    'learn_more': 'மேலும் அறிய',
    'source_label': 'ஆதாரம்: {source}',
  },
  'hi': {
    'welcome_title': 'मोकोगार्ड AI',
    'welcome_tagline': 'ऑफ़लाइन केला पत्ता रोग का पता लगाएं और स्पष्ट व्याख्यात्मक AI प्राप्त करें।',
    'get_started': 'शुरू करें',
    'next': 'आगे',
    'skip': 'छोड़ें',
    'scan_leaves': 'पत्ते स्कैन करें',
    'scan_leaves_desc': 'खेत में संदिग्ध केले के पत्तों की तस्वीरें जल्दी से कैप्चर करें, या एक छवि में कई पत्तों को क्रॉप करें।',
    'detect_disease': 'ऑफ़लाइन पहचान',
    'detect_disease_desc': 'एज एआई बिना इंटरनेट के लक्षणों का विश्लेषण करता है और Grad-CAM हीटमैप दिखाता है।',
    'treat_protect': 'उपचार और सुरक्षा',
    'treat_protect_desc': 'गंभीरता के अनुसार कृषि उपचार दिशानिर्देश पढ़ें और पीडीएफ रिपोर्ट डाउनलोड करें।',
    'welcome_back': 'मोकोगार्ड AI में आपका स्वागत है',
    'offline_intel': 'ऑफ़लाइन केला रोग पहचान और खुफिया तकनीक',
    'weather_alert': 'मौसम अलर्ट: सिगाटोका जोखिम',
    'weather_desc': 'उच्च आर्द्रता (84%) और वर्षा दर्ज की गई। सिगाटोका बीजाणु सक्रिय हैं। पत्तों की जाँच करें।',
    'total_scans': 'कुल स्कैन',
    'healthy': 'स्वस्थ',
    'diseased': 'संक्रमित',
    'moko_wilts': 'मोको विल्ट',
    'disease_dist': 'रोग वितरण',
    'no_dist': 'अभी तक कोई डेटा दर्ज नहीं किया गया है',
    'scan_leaf_btn': 'पत्ता स्कैन करें',
    'full_history_btn': 'पूरा इतिहास',
    'recent_diagnostics': 'हाल के निदान',
    'no_prev_diagnostics': 'कोई पिछला निदान नहीं है',
    'dashboard_tab': 'डैशबोर्ड',
    'guide_tab': 'गाइड',
    'analytics_tab': 'विश्लेषण',
    'settings_tab': 'सेटिंग्स',
    'feedback_prompt': 'क्या यह निदान सही था?',
    'feedback_correct': 'सही वर्ग',
    'feedback_severity': 'सही गंभीरता',
    'feedback_submit': 'प्रतिक्रिया भेजें',
    'feedback_thanks': 'धन्यवाद! आपकी प्रतिक्रिया मोकोगार्ड AI को बेहतर बनाने में मदद करती है।',
    'feedback_privacy': 'प्रतिक्रियाएं आपके डिवाइस पर सुरक्षित रूप से संग्रहीत होती हैं।',
    'feedback_improve': 'सही विवरण प्रदान करके ऐप को बेहतर बनाने में मदद करें:',
    'confidence': 'विश्वास स्तर',
    'disease_Black_Sigatoka': 'ब्लैक सिगाटोका (Black Sigatoka)',
    'disease_Cordana': 'कोर्डाना लीफ स्पॉट (Cordana)',
    'disease_Healthy': 'स्वस्थ पत्ता (Healthy)',
    'disease_Panama_Disease': 'पनामा रोग (Panama Disease)',
    'disease_Pestalotiopsis': 'पेस्टलोटियोप्सिस (Pestalotiopsis)',
    'disease_Yellow_Sigatoka': 'येलो सिगाटोका (Yellow Sigatoka)',
    'disease_Moko': 'मोको रोग (Moko)',
    'severity_Low': 'कम गंभीरता',
    'severity_Medium': 'मध्यम गंभीरता',
    'severity_High': 'उच्च गंभीरता',
    'diagnostic_results': 'निदान परिणाम',
    'low_light_badge': 'लो-लाइट उन्नत',
    'low_light_title': 'कम रोशनी में स्वचालित सुधार',
    'low_light_desc': 'यह फोटो कम रोशनी में ली गई थी और विश्लेषण सटीकता में सुधार के लिए इसे स्वचालित रूप से ठीक किया गया था।',
    'compare_original_enhanced': 'मूल और उन्नत फोटो की तुलना करें',
    'view_mode_original': 'मूल',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': 'गंभीरता',
    'view_mode_combined': 'संयुक्त',
    'view_mode_overlay': 'ओवरले',
    'latency': 'प्रतिक्रिया समय',
    'status': 'स्थिति',
    'status_archived': 'संग्रहीत',
    'status_temporary': 'अस्थायी',
    'save_to_history': 'इतिहास में सहेजें',
    'saved_to_history': 'इतिहास में सहेजा गया',
    'export_pdf_report': 'पीडीएफ रिपोर्ट निर्यात करें',
    'treatment_recommendations': 'उपचार सिफारिशें',
    'enable_research_mode': 'अनुसंधान मोड चालू करें',
    'overlay_opacity': 'अपारदर्शिता',
    'severity_legend': 'गंभीरता रंग संकेतक',
    'legend_low': 'कम / स्वस्थ (<10%)',
    'legend_medium': 'मध्यम (10%-40%)',
    'legend_high': 'उच्च (>40%)',
    'tree_level_diagnosis': 'वृक्ष-स्तरीय निदान',
    'save_tree_to_history': 'पेड़ का इतिहास सहेजें',
    'tree_saved': 'पेड़ का विवरण सहेजा गया',
    'export_aggregated_report': 'aggregated रिपोर्ट निर्यात करें',
    'individual_leaf_breakdown': 'व्यक्तिगत पत्ती विवरण',
    'tree_level_action': 'वृक्ष-स्तरीय कार्रवाई दिशानिर्देश',
    'leaf_crop_num': 'पत्ती का टुकड़ा {number}',
    'leaf_crop_details': 'पत्ती का टुकड़ा #{number} विवरण',
    'probability_distribution': 'संभाव्यता वितरण:',
    'settings_title': 'सेटिंग्स और नियंत्रण',
    'settings_subtitle': 'ऑफ़लाइन मॉडल संस्करण, अनुसंधान मोड और स्थानीय डेटाबेस सेटिंग्स कॉन्फ़िगर करें',
    'appearance_header': 'सजावट',
    'theme_settings': 'थीम सेटिंग्स',
    'theme_dark': 'डार्क मोड सक्रिय',
    'theme_light': 'लाइट मोड सक्रिय',
    'language_settings': 'भाषा सेटिंग्स',
    'language_subtitle': 'ऐप की भाषा चुनें',
    'ai_research_header': 'एआई मॉडल और अनुसंधान उपकरण',
    'model_version_title': 'अनुमान मॉडल संस्करण',
    'model_version_desc': 'ऑफ़लाइन तंत्रिका नेटवर्क फ़ाइल का चयन करें',
    'research_mode_title': 'शैक्षणिक अनुसंधान मोड',
    'research_mode_desc': 'कच्चे आउटपुट और नैदानिक आंकड़े प्रदर्शित करें',
    'image_quality_header': 'छवि गुणवत्ता और सुधार',
    'low_light_enhancement_title': 'ऑटो लो-लाइट सुधार',
    'low_light_enhancement_desc': 'विश्लेषण से पहले अंधेरी या कम कंट्रास्ट वाली तस्वीरों को बेहतर बनाएं',
    'enhancement_strength_title': 'सुधार की तीव्रता',
    'enhancement_strength_desc': 'CLAHE और गामा सुधार स्तर सेट करें',
    'local_data_header': 'स्थानीय डेटा नियंत्रण',
    'export_history_title': 'स्कैन इतिहास निर्यात करें',
    'export_history_desc': 'डेटाबेस लॉग को पोर्टेबल JSON फ़ाइल के रूप में सहेजें',
    'export_feedback_json_title': 'प्रतिक्रिया निर्यात करें (JSON)',
    'export_feedback_json_desc': 'उपयोगकर्ता प्रतिक्रिया लॉग को JSON फ़ाइल के रूप में सहेजें',
    'export_feedback_csv_title': 'प्रतिक्रिया निर्यात करें (CSV)',
    'export_feedback_csv_desc': 'उपयोगकर्ता प्रतिक्रिया लॉग को CSV फ़ाइल के रूप में सहेजें',
    'clear_data_title': 'सभी नैदानिक डेटा साफ़ करें',
    'clear_data_desc': 'स्थानीय नैदानिक डेटा लॉग को स्थायी रूप से रीसेट करें',
    'analytics_title': 'विश्लेषण और रुझान',
    'analytics_subtitle': 'निदान इतिहास विश्लेषण और वृक्षारोपण स्वास्थ्य रुझान',
    'weekly_volume': 'साप्ताहिक निदान मात्रा',
    'weekly_volume_desc': 'पिछले 7 दिनों में प्रतिदिन किए गए पत्ता स्कैन की संख्या',
    'key_indicators': 'प्रमुख स्वास्थ्य संकेतक',
    'healthy_rate_card': 'स्वस्थ फसल दर',
    'primary_threat_card': 'मुख्य खतरा',
    'avg_confidence_card': 'औसत विश्वास',
    'alert_status_card': 'अलर्ट स्थिति',
    'alert_status_low': 'कम',
    'alert_status_warning': 'चेतावनी',
    'alert_status_critical': 'गंभीर',
    'plantation_insight_title': 'वृक्षारोपण अंतर्दृष्टि',
    'insight_empty': 'स्थानीय कृषि अंतर्दृष्टि स्वचालित रूप से उत्पन्न करने के लिए खेत में पत्तों के नमूनों को स्कैन करना शुरू करें।',
    'insight_healthy': 'आपका वृक्षारोपण उत्कृष्ट स्वास्थ्य संकेतक दिखाता है! वर्तमान फसल सुरक्षा प्रोटोकॉल और नियमित सिंचाई बनाए रखें।',
    'insight_critical_desc': 'चेतावनी: {disease} का प्रकोप पाया गया है। तुरंत सभी उपकरणों को कीटाणुरहित करें और प्रभावित क्षेत्रों को अलग करें।',
    'insight_warning_desc': 'कुछ लीफ स्पॉट संक्रमण दर्ज किए गए हैं। माध्यमिक पत्तों की बारीकी से निगरानी करें और संक्रमित भागों को हटाते रहें।',
    'active_learning_card': 'सक्रिय सीखना और उपयोगकर्ता सुधार',
    'active_learning_desc': 'ऑन-डिवाइस उपयोगकर्ता फीडबैक लूप से शैक्षणिक डेटा सत्यापन ट्रैकिंग।',
    'feedback_rate_label': 'फीडबैक दर',
    'logs_count_label': 'लॉग संख्या',
    'thumbs_down_label': 'अस्वीकृत निदान',
    'top_corrections_label': 'शीर्ष उपयोगकर्ता सुधार मैपिंग:',
    'corrections_count': 'सुधार {count}',
    'active_learning_context': 'सक्रिय शिक्षण संदर्भ: ये अज्ञात सुधारात्मक रिकॉर्ड डेटासेट संकलित करने में मदद करते हैं। शोधकर्ता सेटिंग्स में इस डेटा को CSV/JSON के रूप में निर्यात कर सकते हैं।',
    'none': 'कोई नहीं',
    'education_title': 'शिक्षा गाइड',
    'education_subtitle': 'केला रोग के लक्षणों और नियंत्रण विधियों का ऑफ़लाइन डेटाबेस',
    'education_search_hint': 'लक्षणों, रोगजनकों की खोज करें...',
    'no_matches_found': '"{query}" के लिए कोई परिणाम नहीं मिला',
    'prevention_label': 'रोकथाम और नियंत्रण विधियां',
    'cat_Normal_Status': 'सामान्य स्थिति',
    'cat_Bacterial_Wilt': 'बैक्टीरियल विल्ट (उच्च गंभीरता)',
    'cat_Fungal_Wilt': 'कवक जनित विल्ट (उच्च गंभीरता)',
    'cat_Fungal_Leaf_Spot': 'फंगल लीफ स्पॉट',
    'cat_Fungal_Infection': 'कवक संक्रमण',
    'disease_Healthy_symptoms': 'सक्रिय प्रकाश संश्लेषण क्षमता, समान नसों और चिकने किनारों के साथ बेदाग हरे पत्ते। कोई विल्टिंग, पीलापन या सूखा नेक्रोसिस धब्बे नहीं।',
    'disease_Healthy_prevention': 'नियमित सिंचाई बनाए रखें, मिट्टी में NPK स्तर को संतुलित करें, नियमित रूप से निराई करें, और नमी को कम करने के लिए पौधों के बीच पर्याप्त दूरी रखें।',
    'disease_Moko_symptoms': 'भीतर के पत्तों से शुरू होकर पत्ती का तेजी से पीला होना और मुरझाना। पत्तियां डंठल से टूटकर नीचे लटक जाती हैं। काटने पर तने में भूरा संवहनी रंग दिखाई देता है।',
    'disease_Moko_prevention': 'कड़ा संगरोध लागू करें। संक्रमित पौधों को तुरंत नष्ट करें। उपकरणों को 10% फॉर्मलडिहाइड या गर्मी से कीटाणुरहित करें। कीटों को नियंत्रित करें।',
    'disease_Panama_Disease_symptoms': 'पुराने पत्तों के किनारों पर हल्का पीलापन जो मध्य शिरा की ओर बढ़ता है। पत्तियां मुरझा जाती हैं, आधार पर झुक जाती हैं और तने के चारों ओर सूखे पत्तों का घेरा बना लेती हैं। आंतरिक तने में लाल-भूरे रंग की धारियाँ दिखती हैं।',
    'disease_Panama_Disease_prevention': 'प्रमाणित रोग-मुक्त पौधों का उपयोग करें। संक्रमित क्षेत्रों में उपयोग किए गए उपकरणों का उपयोग साफ खेतों में न करें। मिट्टी में ट्राइकोडर्मा जैसे जैव नियंत्रण एजेंटों का उपयोग करें।',
    'disease_Black_Sigatoka_symptoms': 'पत्ते के निचले हिस्से पर छोटे गहरे भूरे रंग के धब्बे जो नसों के समानांतर काली धारियों में बदल जाते हैं। धारियाँ पीले छल्ले के साथ बड़े अंडाकार काले धब्बों में बदल जाती हैं।',
    'disease_Black_Sigatoka_prevention': 'जल निकासी में सुधार करें, नमी कम करने के लिए पुराने पत्तों की छंटाई करें, हवा के प्रवाह के लिए पर्याप्त दूरी रखें और कवकनाशी का उपयोग करें।',
    'disease_Yellow_Sigatoka_symptoms': 'पत्ते की नसों के समानांतर हल्के पीले-हरे रंग की धारियाँ। धारियाँ भूरे रंग के केंद्र, गहरे भूरे किनारों और चमकीले पीले छल्ले के साथ अंडाकार धब्बों में बदल जाती हैं।',
    'disease_Yellow_Sigatoka_prevention': 'संक्रमित हिस्सों को लगातार काटते रहें। खरपतवार नियंत्रण और उर्वरक सुनिश्चित करें। संक्रमण की गंभीरता के अनुसार प्रणालीगत कवकनाशी का उपयोग करें।',
    'disease_Cordana_symptoms': 'आमतौर पर पत्ती के किनारों से शुरू होने वाले बड़े, अंडाकार या पट्टी जैसे धब्बे। धब्बों में हल्के भूरे और गहरे भूरे रंग के छल्लों के साथ एक विशेष ज़िग-ज़ैग रूपरेखा होती है।',
    'disease_Cordana_prevention': 'बीजाणुओं के प्रसार को रोकने के लिए खेत से सूखे पत्तों के मलबे को हटा दें। पत्ती के ऊतकों को मजबूत करने के लिए मिट्टी में पोटेशियम के स्तर को संतुलित रखें।',
    'disease_Pestalotiopsis_symptoms': 'आमतौर पर चोटों या कीट के काटने से शुरू होने वाले सूखे भूरे-भूरे रंग के नेक्रोसिस धब्बे। धब्बे का केंद्र राख-धूसर हो जाता है और छोटे काले बिंदु दिखाई देते हैं।',
    'disease_Pestalotiopsis_prevention': 'परिवहन या निराई के दौरान पत्तियों को चोट लगने से बचाएं। बीजाणुओं के प्रवेश को रोकने के लिए पत्तियों को खाने वाले कीटों को नियंत्रित करें। आवश्यकतानुसार तांबे का छिड़काव करें।',
    'pathogen_label': 'रोगजनक',
    'severity_levels_label': 'गंभीरता के स्तर',
    'symptoms_label': 'लक्षण',
    'management_header': 'प्रबंधन और नियंत्रण',
    'management_cultural': 'कृषि पद्धतियां',
    'management_organic': 'जैविक तरीके',
    'management_chemical': 'रासायनिक तरीके',
    'management_prevention': 'रोकथाम',
    'low': 'कम',
    'medium': 'मध्यम',
    'high': 'उच्च',
    'learn_more': 'अधिक जानें',
    'source_label': 'स्रोत: {source}',
  },
  'id': {
    'welcome_title': 'MokoGuard AI',
    'welcome_tagline': 'Deteksi Penyakit Daun Pisang secara Offline dengan AI yang Dapat Dijelaskan.',
    'get_started': 'Mulai Sekarang',
    'next': 'Lanjut',
    'skip': 'Lewati',
    'scan_leaves': 'Pindai Daun',
    'scan_leaves_desc': 'Ambil foto daun pisang yang mencurigakan di kebun dengan cepat, atau potong beberapa daun sekaligus.',
    'detect_disease': 'Deteksi Offline',
    'detect_disease_desc': 'Edge AI menganalisis gejala secara instan tanpa internet dan menampilkan Grad-CAM heatmap.',
    'treat_protect': 'Rawat & Lindungi',
    'treat_protect_desc': 'Baca panduan perawatan pertanian berdasarkan tingkat keparahan dan ekspor laporan PDF.',
    'welcome_back': 'Selamat Datang di MokoGuard AI',
    'offline_intel': 'Kecerdasan Buatan Deteksi Penyakit Pisang Offline',
    'weather_alert': 'Peringatan Cuaca: Risiko Sigatoka',
    'weather_desc': 'Kelembapan tinggi (84%) & hujan terdeteksi. Spora Sigatoka sangat aktif. Periksa daun bagian dalam.',
    'total_scans': 'Total Pindaian',
    'healthy': 'Sehat',
    'diseased': 'Sakit',
    'moko_wilts': 'Layu Moko',
    'disease_dist': 'Distribusi Penyakit',
    'no_dist': 'Belum ada riwayat pemindaian',
    'scan_leaf_btn': 'Pindai Daun',
    'full_history_btn': 'Riwayat Lengkap',
    'recent_diagnostics': 'Diagnosis Terkini',
    'no_prev_diagnostics': 'Belum ada pemindaian sebelumnya',
    'dashboard_tab': 'Dasbor',
    'guide_tab': 'Panduan',
    'analytics_tab': 'Analisis',
    'settings_tab': 'Pengaturan',
    'feedback_prompt': 'Apakah diagnosis ini benar?',
    'feedback_correct': 'Kelas Benar',
    'feedback_severity': 'Keparahan Benar',
    'feedback_submit': 'Kirim Masukan',
    'feedback_thanks': 'Terima kasih! Masukan Anda membantu meningkatkan akurasi MokoGuard AI.',
    'feedback_privacy': 'Masukan disimpan secara lokal di perangkat ini.',
    'feedback_improve': 'Bantu kami meningkatkan akurasi dengan memberikan detail yang benar:',
    'confidence': 'Tingkat Keyakinan',
    'disease_Black_Sigatoka': 'Sigatoka Hitam (Black Sigatoka)',
    'disease_Cordana': 'Bercak Daun Cordana (Cordana)',
    'disease_Healthy': 'Daun Sehat (Healthy)',
    'disease_Panama_Disease': 'Penyakit Panama (Panama Disease)',
    'disease_Pestalotiopsis': 'Pestalotiopsis',
    'disease_Yellow_Sigatoka': 'Sigatoka Kuning (Yellow Sigatoka)',
    'disease_Moko': 'Penyakit Moko (Moko)',
    'severity_Low': 'Keparahan Rendah',
    'severity_Medium': 'Keparahan Sedang',
    'severity_High': 'Keparahan Tinggi',
    'diagnostic_results': 'Hasil Diagnosis',
    'low_light_badge': 'Peningkatan Pencahayaan Rendah',
    'low_light_title': 'Peningkatan Otomatis Cahaya Rendah',
    'low_light_desc': 'Foto ini diambil dalam kondisi cahaya redup dan disempurnakan secara otomatis untuk meningkatkan akurasi diagnosis.',
    'compare_original_enhanced': 'Bandingkan Asli vs Ditingkatkan',
    'view_mode_original': 'Asli',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': 'Keparahan',
    'view_mode_combined': 'Gabungan',
    'view_mode_overlay': 'Hamparan',
    'latency': 'Waktu Latensi',
    'status': 'Status',
    'status_archived': 'Diarsipkan',
    'status_temporary': 'Sementara',
    'save_to_history': 'Simpan ke Riwayat',
    'saved_to_history': 'Disimpan ke Riwayat',
    'export_pdf_report': 'Ekspor Laporan PDF',
    'treatment_recommendations': 'Rekomendasi Perawatan',
    'enable_research_mode': 'Aktifkan Mode Riset',
    'overlay_opacity': 'Opasitas Hamparan',
    'severity_legend': 'Legenda Warna Keparahan',
    'legend_low': 'Rendah / Sehat (<10%)',
    'legend_medium': 'Sedang (10%-40%)',
    'legend_high': 'Tinggi (>40%)',
    'tree_level_diagnosis': 'Diagnosis Tingkat Pohon',
    'save_tree_to_history': 'Simpan Pohon ke Riwayat',
    'tree_saved': 'Pohon Disimpan',
    'export_aggregated_report': 'Ekspor Laporan Gabungan',
    'individual_leaf_breakdown': 'Rincian Daun Individu',
    'tree_level_action': 'Panduan Tindakan Tingkat Pohon',
    'leaf_crop_num': 'Potongan Daun {number}',
    'leaf_crop_details': 'Detail Potongan Daun #{number}',
    'probability_distribution': 'Distribusi Probabilitas:',
    'settings_title': 'Pengaturan & Kontrol',
    'settings_subtitle': 'Konfigurasikan versi model offline, mode riset, dan pengaturan database lokal',
    'appearance_header': 'Tampilan',
    'theme_settings': 'Pengaturan Tema',
    'theme_dark': 'Mode Gelap Aktif',
    'theme_light': 'Mode Terang Aktif',
    'language_settings': 'Pengaturan Bahasa',
    'language_subtitle': 'Pilih bahasa aplikasi',
    'ai_research_header': 'Model AI & Alat Riset',
    'model_version_title': 'Versi Model Inferensi',
    'model_version_desc': 'Pilih file jaringan saraf offline',
    'research_mode_title': 'Mode Riset Akademik',
    'research_mode_desc': 'Tampilkan distribusi logit keluaran mentah & statistik diagnostik',
    'image_quality_header': 'Kualitas & Peningkatan Gambar',
    'low_light_enhancement_title': 'Peningkatan Cahaya Rendah Otomatis',
    'low_light_enhancement_desc': 'Tingkatkan foto gelap atau kontras rendah sebelum analisis',
    'enhancement_strength_title': 'Kekuatan Peningkatan',
    'enhancement_strength_desc': 'Atur tingkat koreksi CLAHE & Gamma',
    'local_data_header': 'Kontrol Data Lokal',
    'export_history_title': 'Ekspor Riwayat Pemindaian',
    'export_history_desc': 'Simpan log database sebagai file JSON portabel',
    'export_feedback_json_title': 'Ekspor Masukan (JSON)',
    'export_feedback_json_desc': 'Simpan log masukan pengguna sebagai file JSON',
    'export_feedback_csv_title': 'Ekspor Masukan (CSV)',
    'export_feedback_csv_desc': 'Simpan log masukan pengguna sebagai file CSV tabular',
    'clear_data_title': 'Hapus Semua Data Diagnostik',
    'clear_data_desc': 'Setel ulang log database pemindaian secara permanen',
    'analytics_title': 'Analisis & Tren',
    'analytics_subtitle': 'Analisis Riwayat Diagnosis dan Tren Kesehatan Perkebunan',
    'weekly_volume': 'Volume Diagnosis Mingguan',
    'weekly_volume_desc': 'Jumlah pemindaian daun yang dilakukan setiap hari selama 7 hari terakhir',
    'key_indicators': 'Indikator Kesehatan Utama',
    'healthy_rate_card': 'Tingkat Tanaman Sehat',
    'primary_threat_card': 'Ancaman Utama',
    'avg_confidence_card': 'Rata-rata Keyakinan',
    'alert_status_card': 'Status Peringatan',
    'alert_status_low': 'RENDAH',
    'alert_status_warning': 'PERINGATAN',
    'alert_status_critical': 'KRITIS',
    'plantation_insight_title': 'Wawasan Perkebunan',
    'insight_empty': 'Mulai pindai sampel daun di lapangan untuk secara otomatis menghasilkan wawasan pertanian lokal di sini.',
    'insight_healthy': 'Perkebunan Anda menunjukkan metrik kesehatan yang sangat baik! Pertahankan protokol perlindungan tanaman saat ini dan irigasi rutin.',
    'insight_critical_desc': 'Peringatan: Wabah {disease} terdeteksi. Segera bersihkan semua alat dengan sterilisator dan isolasi zona yang terkena dampak.',
    'insight_warning_desc': 'Beberapa infeksi bercak daun telah tercatat. Pantau daun sekunder dengan cermat dan terus pangkas bagian yang terinfeksi.',
    'active_learning_card': 'Pembelajaran Aktif & Koreksi Pengguna',
    'active_learning_desc': 'Pelacakan validasi data akademis dari loop umpan balik pengguna di perangkat.',
    'feedback_rate_label': 'Tingkat Umpan Balik',
    'logs_count_label': 'Jumlah Log',
    'thumbs_down_label': 'Koreksi Negatif',
    'top_corrections_label': 'Pemetaan Koreksi Pengguna Teratas:',
    'corrections_count': '{count} koreksi',
    'active_learning_context': 'Konteks Pembelajaran Aktif: Catatan korektif yang dianonimkan ini membantu menyusun himpunan data berkualitas tinggi. Peneliti dapat mengekspor data ini di Pengaturan sebagai CSV/JSON untuk melakukan penyetelan halus pembelajaran aktif untuk iterasi CNN berikutnya.',
    'none': 'Tidak Ada',
    'education_title': 'Panduan Edukasi',
    'education_subtitle': 'Database Offline Gejala Penyakit Pisang dan Metode Pengendaliannya',
    'education_search_hint': 'Cari gejala, patogen...',
    'no_matches_found': 'Tidak ada kecocokan ditemukan untuk "{query}"',
    'prevention_label': 'Metode Pencegahan & Pengendalian',
    'cat_Normal_Status': 'Status Normal',
    'cat_Bacterial_Wilt': 'Layu Bakteri (Keparahan Tinggi)',
    'cat_Fungal_Wilt': 'Layu Jamur (Keparahan Tinggi)',
    'cat_Fungal_Leaf_Spot': 'Bercak Daun Jamur',
    'cat_Fungal_Infection': 'Infeksi Jamur',
    'disease_Healthy_symptoms': 'Helaian daun hijau mulus dengan kapasitas fotosintesis aktif, pertulangan daun seragam, dan tepi halus. Tidak ada kelayuan, pinggiran menguning, atau bercak nekrosis kering.',
    'disease_Healthy_prevention': 'Pertahankan irigasi teratur, seimbangkan kadar NPK tanah, bersihkan gulma secara teratur, dan jaga jarak tanam yang cukup untuk meminimalkan akumulasi kelembapan.',
    'disease_Moko_symptoms': 'Menguning dan melayunya helaian daun secara cepat, dimulai dari daun bagian dalam. Daun patah pada tangkai dan menggantung. Batang menunjukkan perubahan warna vaskular cokelat saat dipotong.',
    'disease_Moko_prevention': 'Terapkan karantina ketat. Hancurkan tanaman terinfeksi segera. Sterilkan alat pertanian dengan formaldehida 10% atau panas sebelum berpindah ke pohon bersih. Kendalikan vektor serangga.',
    'disease_Panama_Disease_symptoms': 'Menguning samar pada tepi daun yang lebih tua, berkembang ke arah tulang daun. Daun layu, terkulai di pangkal, membentuk rok daun mati di sekitar batang semu. Batang bagian dalam menunjukkan garis kemerahan.',
    'disease_Panama_Disease_prevention': 'Gunakan bibit kultur jaringan bersertifikat bebas penyakit. Hindari alat di kebun bersih yang telah digunakan di zona terinfeksi. Oleskan agen biokontrol Trichoderma ke tanah.',
    'disease_Black_Sigatoka_symptoms': 'Bercak cokelat tua kecil di sisi bawah daun, berkembang menjadi garis-garis gelap sejajar dengan tulang daun. Garis melebar menjadi bercak hitam elips besar dengan tepi basah dan lingkaran kuning.',
    'disease_Black_Sigatoka_prevention': 'Tingkatkan drainase lahan, pangkas daun tua untuk mengurangi kelembapan, atur jarak untuk mengoptimalkan aliran udara, dan gunakan fungisida organik/kimia di musim berisiko tinggi.',
    'disease_Yellow_Sigatoka_symptoms': 'Garis hijau kekuningan pucat sejajar dengan tulang daun. Garis melebar menjadi bercak elips dengan pusat abu-abu terang, batas cokelat tua, dan lingkaran kuning cerah.',
    'disease_Yellow_Sigatoka_prevention': 'Pangkas bagian terinfeksi terus-menerus. Pastikan pengendalian gulma dan pemupukan efisien agar pohon tetap kuat. Gunakan fungisida sistemik atau kontak tergantung pada indeks infeksi.',
    'disease_Cordana_symptoms': 'Bercak besar, oval atau seperti pita, biasanya dimulai dari tepi daun. Bercak memiliki garis zig-zag khas dengan cincin konsentris abu-abu terang dan cokelat tua.',
    'disease_Cordana_prevention': 'Bersihkan serasah daun mati dari lantai perkebunan untuk mencegah penyebaran spora. Jaga keseimbangan kadar kalium tanah untuk memperkuat jaringan daun.',
    'disease_Pestalotiopsis_symptoms': 'Bercak nekrosis cokelat keabu-abuan kering, biasanya dimulai dari luka mekanis atau gigitan serangga. Pusat bercak berubah menjadi abu-abu abu dengan titik hitam kecil.',
    'disease_Pestalotiopsis_prevention': 'Hindari luka fisik daun saat transportasi atau penyiangan. Kendalikan hama pemakan daun yang membuat titik masuk spora. Gunakan semprotan tembaga pelindung jika menyebar luas.',
    'pathogen_label': 'Patogen',
    'severity_levels_label': 'Tingkat Keparahan',
    'symptoms_label': 'Gejala',
    'management_header': 'Pengendalian & Perawatan',
    'management_cultural': 'Praktik Budidaya',
    'management_organic': 'Metode Organik',
    'management_chemical': 'Metode Kimia',
    'management_prevention': 'Pencegahan',
    'low': 'Rendah',
    'medium': 'Sedang',
    'high': 'Tinggi',
    'learn_more': 'Pelajari Selengkapnya',
    'source_label': 'Sumber: {source}',
  },
  'zh': {
    'welcome_title': 'MokoGuard AI',
    'welcome_tagline': '离线检测香蕉叶片疾病并提供可解释的 AI 分析。',
    'get_started': '开始使用',
    'next': '下一步',
    'skip': '跳过',
    'scan_leaves': '扫描叶片',
    'scan_leaves_desc': '在果园中快速捕捉可疑香蕉叶片的照片，或在单张图像中裁剪多片叶片。',
    'detect_disease': '离线检测',
    'detect_disease_desc': '边缘 AI 在无网络状态下即时分析症状，并通过 Grad-CAM 热力图突出病斑。',
    'treat_protect': '治疗与保护',
    'treat_protect_desc': '阅读根据严重程度定制的农业治疗指南，并导出 PDF 报告。',
    'welcome_back': '欢迎使用 MokoGuard AI',
    'offline_intel': '香蕉疾病离线可解释智能检测系统',
    'weather_alert': '天气预警：叶斑病风险',
    'weather_desc': '检测到高湿度（84%）和降雨。叶斑病孢子高度活跃，请检查内侧叶片。',
    'total_scans': '总扫描数',
    'healthy': '健康',
    'diseased': '患病',
    'moko_wilts': '莫科维尔特病',
    'disease_dist': '疾病分布',
    'no_dist': '暂无检测记录',
    'scan_leaf_btn': '扫描叶片',
    'full_history_btn': '完整历史',
    'recent_diagnostics': '最近检测',
    'no_prev_diagnostics': '暂无历史检测',
    'dashboard_tab': '仪表板',
    'guide_tab': '指南',
    'analytics_tab': '分析',
    'settings_tab': '设置',
    'feedback_prompt': '此诊断是否正确？',
    'feedback_correct': '正确的类别',
    'feedback_severity': '正确的严重程度',
    'feedback_submit': '提交反馈',
    'feedback_thanks': '谢谢！您的反馈有助于改进 MokoGuard AI。',
    'feedback_privacy': '反馈数据仅本地保存在此设备上。',
    'feedback_improve': '提供正确的详细信息以帮助我们改进此应用：',
    'confidence': '置信度',
    'disease_Black_Sigatoka': '黑条叶斑病 (Black Sigatoka)',
    'disease_Cordana': '寇氏叶斑病 (Cordana)',
    'disease_Healthy': '健康叶片 (Healthy)',
    'disease_Panama_Disease': '巴拿马病 (Panama Disease)',
    'disease_Pestalotiopsis': '拟盘多毛孢褐斑病 (Pestalotiopsis)',
    'disease_Yellow_Sigatoka': '黄条叶斑病 (Yellow Sigatoka)',
    'disease_Moko': '莫科病 (Moko)',
    'severity_Low': '低严重度',
    'severity_Medium': '中严重度',
    'severity_High': '高严重度',
    'diagnostic_results': '诊断结果',
    'low_light_badge': '微光增强',
    'low_light_title': '微光自动增强',
    'low_light_desc': '这张照片是在光线不足的情况下拍摄的，已自动进行增强以提高诊断准确性。',
    'compare_original_enhanced': '对比原图与增强图',
    'view_mode_original': '原图',
    'view_mode_gradcam': 'Grad-CAM',
    'view_mode_severity': '严重程度',
    'view_mode_combined': '混合视图',
    'view_mode_overlay': '覆盖层',
    'latency': '推理延迟',
    'status': '状态',
    'status_archived': '已保存',
    'status_temporary': '临时记录',
    'save_to_history': '保存到历史记录',
    'saved_to_history': '已保存到历史',
    'export_pdf_report': '导出 PDF 报告',
    'treatment_recommendations': '防治建议',
    'enable_research_mode': '启用学术研究模式',
    'overlay_opacity': '覆盖图不透明度',
    'severity_legend': '严重度颜色图例',
    'legend_low': '轻微 / 健康 (<10%)',
    'legend_medium': '中度 (10%-40%)',
    'legend_high': '重度 (>40%)',
    'tree_level_diagnosis': '整株树体级诊断',
    'save_tree_to_history': '保存整株记录至历史',
    'tree_saved': '整株已保存',
    'export_aggregated_report': '导出聚合报告',
    'individual_leaf_breakdown': '单片叶片明细',
    'tree_level_action': '整株树体级防治指南',
    'leaf_crop_num': '叶片裁剪区域 {number}',
    'leaf_crop_details': '叶片裁剪区域 #{number} 详情',
    'probability_distribution': '概率分布特征：',
    'settings_title': '设置与控制项',
    'settings_subtitle': '配置离线模型版本、学术研究模式和本地数据库设置',
    'appearance_header': '外观设置',
    'theme_settings': '主题设置',
    'theme_dark': '深色模式已启用',
    'theme_light': '浅色模式已启用',
    'language_settings': '语言设置',
    'language_subtitle': '选择应用程序语言',
    'ai_research_header': 'AI 模型与研究工具',
    'model_version_title': '推理模型版本',
    'model_version_desc': '选择离线神经网络模型文件',
    'research_mode_title': '学术研究模式',
    'research_mode_desc': '显示原始输出概率分布与诊断统计数据',
    'image_quality_header': '图像质量与增强',
    'low_light_enhancement_title': '自动微光增强',
    'low_light_enhancement_desc': '在分析前自动改善暗光或低对比度照片',
    'enhancement_strength_title': '增强强度级别',
    'enhancement_strength_desc': '设置 CLAHE 对比度限制与伽马校正系数',
    'local_data_header': '本地数据管理',
    'export_history_title': '导出扫描历史记录',
    'export_history_desc': '将本地数据库日志保存为便携式 JSON 文件',
    'export_feedback_json_title': '导出反馈日志 (JSON)',
    'export_feedback_json_desc': '将用户反馈记录保存为 JSON 文件',
    'export_feedback_csv_title': '导出反馈日志 (CSV)',
    'export_feedback_csv_desc': '将用户反馈记录保存为表格 CSV 文件',
    'clear_data_title': '清除所有诊断记录',
    'clear_data_desc': '永久重置本地扫描数据库日志',
    'analytics_title': '分析与趋势',
    'analytics_subtitle': '诊断历史分析与蕉园健康趋势',
    'weekly_volume': '每周诊断量',
    'weekly_volume_desc': '过去 7 天内每日进行的叶片扫描次数',
    'key_indicators': '关键健康指标',
    'healthy_rate_card': '健康作物率',
    'primary_threat_card': '主要威胁',
    'avg_confidence_card': '平均置信度',
    'alert_status_card': '警报状态',
    'alert_status_low': '低',
    'alert_status_warning': '警告',
    'alert_status_critical': '严重',
    'plantation_insight_title': '蕉园洞察',
    'insight_empty': '开始扫描田间的叶片样本，在此自动生成本地农业洞察。',
    'insight_healthy': '您的蕉园显示出卓越的健康指标！请保持现有的作物保护措施与常规灌溉。',
    'insight_critical_desc': '警告：检测到 {disease} 爆发。请立即使用消毒剂清洁所有工具，并隔离受影响的区域。',
    'insight_warning_desc': '已记录到少量叶斑病感染。请密切监测次生叶片，并持续剪除受感染的部分。',
    'active_learning_card': '主动学习与用户纠偏',
    'active_learning_desc': '来自设备端用户反馈回路的学术数据校验跟踪。',
    'feedback_rate_label': '反馈率',
    'logs_count_label': '日志数量',
    'thumbs_down_label': '用户纠偏数',
    'top_corrections_label': '主要用户纠偏映射关系：',
    'corrections_count': '{count} 次纠偏',
    'active_learning_context': '主动学习背景：这些匿名化的纠偏记录有助于构建高保真数据集。研究人员可在设置中将此数据导出为 CSV/JSON，以便为后续的 CNN 迭代进行主动学习微调。',
    'none': '无',
    'education_title': '科普指南',
    'education_subtitle': '香蕉叶片疾病症状与防治方法离线数据库',
    'education_search_hint': '搜索症状、病原体...',
    'no_matches_found': '未找到与 "{query}" 匹配的结果',
    'prevention_label': '防治与控制方法',
    'cat_Normal_Status': '正常状态',
    'cat_Bacterial_Wilt': '细菌性枯萎病 (重度)',
    'cat_Fungal_Wilt': '真菌性枯萎病 (重度)',
    'cat_Fungal_Leaf_Spot': '真菌性叶斑病',
    'cat_Fungal_Infection': '真菌感染',
    'disease_Healthy_symptoms': '绿色叶片完好无损，具有活跃的光合作用能力，叶脉均匀，边缘光滑。无萎蔫、边缘发黄或干燥坏死斑点。',
    'disease_Healthy_prevention': '保持规律的灌溉，平衡土壤中的 NPK 水平，定期除草，并保持树木之间足够的间距以减少湿度积聚。',
    'disease_Moko_symptoms': '叶片迅速变黄萎蔫，从内叶开始。叶片在叶柄处折断并下垂。切开茎部时显示褐色维管束变色。',
    'disease_Moko_prevention': '实施严格的检疫。立即销毁受感染植株。在移动到健康植株前，使用 10% 甲醛或加热消毒农具。控制昆虫媒介。',
    'disease_Panama_Disease_symptoms': '老叶边缘轻微发黄，向中脉延伸。叶片萎蔫，在叶基部折断，在假茎周围形成一圈死叶。假茎内部显示红褐色条纹。',
    'disease_Panama_Disease_prevention': '使用经过认证的无病组培苗。避免在干净的田地中使用曾用于受感染区域的工具。向土壤中施用木霉菌等生物防治剂。',
    'disease_Black_Sigatoka_symptoms': '叶背出现微小的深褐色斑点，逐渐发展为与叶脉平行的深色条纹。条纹扩大为椭圆形黑斑，边缘呈水渍状并有黄色晕圈。',
    'disease_Black_Sigatoka_prevention': '改善田间排水，修剪老叶以降低湿度，合理密植以优化空气流动，并在高风险季节使用化学或有机杀菌剂。',
    'disease_Yellow_Sigatoka_symptoms': '与叶脉平行的淡黄绿色条纹。条纹扩大为椭圆形斑点，中心呈浅灰色，边缘呈深褐色，并有鲜黄色晕圈。',
    'disease_Yellow_Sigatoka_prevention': '持续清除受感染的部分。确保有效的杂草控制和施肥以保持树木健壮。根据感染指数使用内戏性或触杀性杀菌剂。',
    'disease_Cordana_symptoms': '大块的椭圆形或条带状斑点，通常从叶缘开始。斑点具有特征性的呈锯齿状的同心圆环，呈浅灰色和深褐色交替。',
    'disease_Cordana_prevention': '从蕉园地面清除死叶碎片，防止孢子散播。保持土壤中钾水平平衡，以增强叶片组织。',
    'disease_Pestalotiopsis_symptoms': '干燥的灰褐色坏死斑点，通常从机械伤口或昆虫咬伤处开始。斑点中心变为灰白色，并有微小的黑色针尖状物（孢子结构）。',
    'disease_Pestalotiopsis_prevention': '避免在运输或除草过程中对叶片造成机械损伤。管理造成孢子入侵伤口的食叶害虫。若大面积发生，喷施保护性铜制剂。',
    'pathogen_label': '病原体',
    'severity_levels_label': '严重程度分级',
    'symptoms_label': '主要症状',
    'management_header': '综合防治措施',
    'management_cultural': '农业防治',
    'management_organic': '生物/有机防治',
    'management_chemical': '化学防治',
    'management_prevention': '预防措施',
    'low': '轻度',
    'medium': '中度',
    'high': '重度',
    'learn_more': '查看详情',
    'source_label': '来源: {source}',
  },
};

String getTranslation(String key, String locale) {
  final Map<String, String>? localMap = _translations[locale];
  if (localMap != null && localMap.containsKey(key)) {
    return localMap[key]!;
  }
  // Fallback to English
  final Map<String, String>? engMap = _translations['en'];
  if (engMap != null && engMap.containsKey(key)) {
    return engMap[key]!;
  }
  return key;
}
